### ISSUE TITLE
Crash when cloning custom trait

### ISSUE THREAD

**Issue by swilcox3** [Diggsey/query_interface#5]
I'm very interested in this library, it provides a key functionality I need in my project, but I've encountered a panic when cloning a custom trait object.  Based on the examples in the docs, this should work:

```
use query_interface::*;

trait Test : Object + ObjectClone + HasInterface<ObjectClone> {
}

mopo!(Test);

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
struct Obj;

interfaces!(Obj: ObjectClone, std::fmt::Debug);

impl Test for Obj {
}

#[test]
fn minimum_case() {
    let obj = Box::new(Obj) as Box<Test>;
    let obj2 = obj.clone();
}
```

The above code will panic on the clone() call, with this callstack:

thread 'tests::minimum_case' panicked at 'called `Result::unwrap()` on an `Err` value: Obj', src\libcore\result.rs:999:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\sys\windows\backtrace\mod.rs:95
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\sys\windows\backtrace\mod.rs:82
   2: std::sys_common::backtrace::_print
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::print
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\sys_common\backtrace.rs:59
   4: std::panicking::default_hook::{{closure}}
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\panicking.rs:197
   5: std::panicking::default_hook
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\panicking.rs:381
   8: std::panicking::rust_begin_panic
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libstd\panicking.rs:308
   9: core::panicking::panic_fmt
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libcore\panicking.rs:85
  10: core::result::unwrap_failed<alloc::boxed::Box<Object>>
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\src\libcore\macros.rs:18
  11: core::result::Result<alloc::boxed::Box<Test>, alloc::boxed::Box<Object>>::unwrap<alloc::boxed::Box<Test>,alloc::boxed::Box<Object>>
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\src\libcore\result.rs:800
  12: data_manager::tests::{{impl}}::to_owned
             at <::query_interface::mopo macros>:62
  13: data_manager::tests::{{impl}}::clone
             at <::query_interface::mopo macros>:59
  14: data_manager::tests::minimum_case
             at .\src\tests.rs:121
  15: data_manager::tests::minimum_case::{{closure}}
             at .\src\tests.rs:119
  16: core::ops::function::FnOnce::call_once<closure,()>
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\src\libcore\ops\function.rs:231
  17: alloc::boxed::{{impl}}::call_once<(),FnBox<()>>
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\src\liballoc\boxed.rs:704
  18: panic_unwind::__rust_maybe_catch_panic
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libpanic_unwind\lib.rs:85
  19: std::panicking::try
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\src\libstd\panicking.rs:272
  20: std::panic::catch_unwind
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\src\libstd\panic.rs:388
  21: test::run_test::run_test_inner::{{closure}}
             at /rustc/70f130954d6fd36fe3e77f4b5b33e5af50489288\/src\libtest\lib.rs:1468

**Comment by swilcox3** [comment]
Never mind, I'm dumb, I missed the part where you have to put the custom trait in the interfaces! macro.
